export const xianData = {
    "zhengdiao": [
        {
            id: 1,
            name: "一弦",
            char: "C2",
            sound: -33,
        },
        {
            id: 2,
            name: "二弦",
            char: "D2",
            sound: -31,
        },
        {
            id: 3,
            name: "三弦",
            char: "F2",
            sound: -28,
        },
        {
            id: 4,
            name: "四弦",
            char: "G2",
            sound: -26,
        },
        {
            id: 5,
            name: "五弦",
            char: "A2",
            sound: -22,
        },
        {
            id: 6,
            name: "六弦",
            char: "C3",
            sound: -21,
        },
        {
            id: 7,
            name: "七弦",
            char: "D3",
            sound: -19,
        },
    ],
    "jin5xian": [
        {
            id: 1,
            name: "一弦",
            char: "C2",
            sound: -33,
        },
        {
            id: 2,
            name: "二弦",
            char: "D2",
            sound: -31,
        },
        {
            id: 3,
            name: "三弦",
            char: "F2",
            sound: -28,
        },
        {
            id: 4,
            name: "四弦",
            char: "G2",
            sound: -26,
        },
        {
            id: 5,
            name: "五弦",
            char: "bB2",
            sound: -23,
        },
        {
            id: 6,
            name: "六弦",
            char: "C3",
            sound: -21,
        },
        {
            id: 7,
            name: "七弦",
            char: "D3",
            sound: -19,
        },
    ],
    "man36xian": [
        {
            id: 1,
            name: "一弦",
            char: "C2",
            sound: -33,
        },
        {
            id: 2,
            name: "二弦",
            char: "D2",
            sound: -31,
        },
        {
            id: 3,
            name: "三弦",
            char: "E2",
            sound: -29,
        },
        {
            id: 4,
            name: "四弦",
            char: "G2",
            sound: -26,
        },
        {
            id: 5,
            name: "五弦",
            char: "A2",
            sound: -22,
        },
        {
            id: 6,
            name: "六弦",
            char: "B2",
            sound: -22,
        },
        {
            id: 7,
            name: "七弦",
            char: "D3",
            sound: -19,
        },
    ],
    "man6xian": [
        {
            id: 1,
            name: "一弦",
            char: "C2",
            sound: -33,
        },
        {
            id: 2,
            name: "二弦",
            char: "D2",
            sound: -31,
        },
        {
            id: 3,
            name: "三弦",
            char: "F2",
            sound: -28,
        },
        {
            id: 4,
            name: "四弦",
            char: "G2",
            sound: -26,
        },
        {
            id: 5,
            name: "五弦",
            char: "A2",
            sound: -22,
        },
        {
            id: 6,
            name: "六弦",
            char: "B2",
            sound: -22,
        },
        {
            id: 7,
            name: "七弦",
            char: "D3",
            sound: -19,
        },
    ],
    "man3xian": [
        {
            id: 1,
            name: "一弦",
            char: "C2",
            sound: -33,
        },
        {
            id: 2,
            name: "二弦",
            char: "D2",
            sound: -31,
        },
        {
            id: 3,
            name: "三弦",
            char: "E2",
            sound: -29,
        },
        {
            id: 4,
            name: "四弦",
            char: "G2",
            sound: -26,
        },
        {
            id: 5,
            name: "五弦",
            char: "A2",
            sound: -22,
        },
        {
            id: 6,
            name: "六弦",
            char: "C3",
            sound: -21,
        },
        {
            id: 7,
            name: "七弦",
            char: "D3",
            sound: -19,
        },
    ],
}